namespace WFC {
    export class tile {
        bitmap: Image
        constructor(
            public name: string,
            public symmetry: string,
            public weight: number
        ) {
            this.bitmap = helpers.getImageByName(this.name)
            screen.drawImage(this.bitmap,0,0)
        }
    }

    export class neighbor {
        constructor(
            public left: string,
            public right: string
        ) { }
    }
    export class subset {
        constructor(
            public name: string,
            public tile: string[]
        ) { }
    }
    export class Data {
        public unique: boolean
        constructor(
            public tilesize: number = 14,
            public tiles: tile[],
            public neighbors: neighbor[],
            public subsets:  {[index: string]: string[]}
        ) {
            this.unique == false
        }
    }

    export let dataCircuit = new Data(
        14,
        [
            new tile("bridge", "I", 1.0),
            new tile("component", "X", 20.0),
            new tile("connection", "T", 10.0),
            new tile("corner", "L", 10.0),
            new tile("substrate", "X", 2.0),
            new tile("t", "T", 0.1),
            new tile("track", "I", 2.0),
            new tile("transition", "T", 0.4),
            new tile("turn", "L", 1.0),
            new tile("viad", "I", 0.1),
            new tile("vias", "T", 0.3),
            new tile("wire", "I", 0.5),
            new tile("skew", "L", 2.0),
            new tile("dskew", "\\", 2.0)
        ],
        [
            new neighbor("bridge", "bridge"),
            new neighbor("bridge 1", "bridge 1"),
            new neighbor("bridge 1", "connection 1"),
            new neighbor("bridge 1", "t 2"),
            new neighbor("bridge 1", "t 3"),
            new neighbor("bridge 1", "track 1"),
            new neighbor("bridge", "transition 1"),
            new neighbor("bridge 1", "turn 1"),
            new neighbor("bridge 1", "viad"),
            new neighbor("bridge 1", "vias 1"),
            new neighbor("bridge", "wire"),
            new neighbor("component", "component"),
            new neighbor("connection 1", "component"),
            new neighbor("connection", "connection"),
            new neighbor("connection", "corner"),
            new neighbor("t 1", "connection 1"),
            new neighbor("t 2", "connection 1"),
            new neighbor("track 1", "connection 1"),
            new neighbor("turn", "connection 1"),
            new neighbor("substrate", "corner 1"),
            new neighbor("t 3", "corner 1"),
            new neighbor("track", "corner 1"),
            new neighbor("transition 2", "corner 1"),
            new neighbor("transition", "corner 1"),
            new neighbor("turn 1", "corner 1"),
            new neighbor("turn 2", "corner 1"),
            new neighbor("viad 1", "corner 1"),
            new neighbor("vias 1", "corner 1"),
            new neighbor("vias 2", "corner 1"),
            new neighbor("vias", "corner 1"),
            new neighbor("wire 1", "corner 1"),
            new neighbor("substrate", "substrate"),
            new neighbor("substrate", "t 1"),
            new neighbor("substrate", "track"),
            new neighbor("substrate", "transition 2"),
            new neighbor("substrate", "turn"),
            new neighbor("substrate", "viad 1"),
            new neighbor("substrate", "vias 2"),
            new neighbor("substrate", "vias 3"),
            new neighbor("substrate", "wire 1"),
            new neighbor("t 1", "t 3"),
            new neighbor("t 3", "t 1"),
            new neighbor("t 1", "t 2"),
            new neighbor("t 2", "t 2"),
            new neighbor("t 2", "t"),
            new neighbor("t 3", "track"),
            new neighbor("t 1", "track 1"),
            new neighbor("t 2", "track 1"),
            new neighbor("t 1", "transition 3"),
            new neighbor("t 3", "transition 2"),
            new neighbor("t 2", "transition 3"),
            new neighbor("t 3", "turn"),
            new neighbor("t 1", "turn 1"),
            new neighbor("t 2", "turn 1"),
            new neighbor("t 2", "turn 2"),
            new neighbor("t 3", "viad 1"),
            new neighbor("t 1", "viad"),
            new neighbor("t 2", "viad"),
            new neighbor("t 2", "vias 1"),
            new neighbor("t 1", "vias 1"),
            new neighbor("vias 1", "t 1"),
            new neighbor("vias 2", "t 1"),
            new neighbor("wire 1", "t 1"),
            new neighbor("track", "track"),
            new neighbor("track 1", "track 1"),
            new neighbor("track 1", "transition 3"),
            new neighbor("track", "transition 2"),
            new neighbor("track", "turn"),
            new neighbor("track 1", "turn 1"),
            new neighbor("track", "viad 1"),
            new neighbor("track 1", "viad"),
            new neighbor("track", "vias 2"),
            new neighbor("track", "vias 3"),
            new neighbor("track 1", "vias 1"),
            new neighbor("track", "wire 1"),
            new neighbor("transition 2", "turn"),
            new neighbor("transition", "turn"),
            new neighbor("transition 1", "turn 1"),
            new neighbor("transition 2", "viad 1"),
            new neighbor("transition 2", "vias 2"),
            new neighbor("transition 2", "vias 3"),
            new neighbor("transition 2", "vias"),
            new neighbor("wire", "transition 1"),
            new neighbor("transition 2", "wire 1"),
            new neighbor("turn 1", "turn"),
            new neighbor("turn 2", "turn"),
            new neighbor("turn", "turn 1"),
            new neighbor("turn", "turn 2"),
            new neighbor("turn 1", "viad 1"),
            new neighbor("turn", "viad"),
            new neighbor("turn 1", "vias 2"),
            new neighbor("turn 1", "vias 3"),
            new neighbor("turn 1", "vias"),
            new neighbor("turn", "vias 1"),
            new neighbor("turn 1", "wire 1"),
            new neighbor("viad 1", "viad 1"),
            new neighbor("viad 1", "vias 2"),
            new neighbor("viad 1", "vias 3"),
            new neighbor("viad 1", "wire 1"),
            new neighbor("vias 1", "wire 1"),
            new neighbor("vias 2", "wire 1"),
            new neighbor("vias 1", "vias 3"),
            new neighbor("vias 2", "vias 2"),
            new neighbor("vias 2", "vias"),
            new neighbor("wire", "wire"),
            new neighbor("wire 1", "wire 1"),
            new neighbor("bridge 1", "dskew"),
            new neighbor("connection 3", "dskew"),
            new neighbor("dskew", "dskew"),
            new neighbor("skew", "dskew"),
            new neighbor("t", "dskew"),
            new neighbor("t 2", "dskew"),
            new neighbor("t 1", "dskew"),
            new neighbor("track 1", "dskew"),
            new neighbor("transition 1", "dskew"),
            new neighbor("turn 3", "dskew"),
            new neighbor("viad", "dskew"),
            new neighbor("vias 3", "dskew"),
            new neighbor("skew", "bridge 1"),
            new neighbor("skew", "connection 1"),
            new neighbor("corner", "skew"),
            new neighbor("corner 3", "skew"),
            new neighbor("skew", "dskew"),
            new neighbor("skew", "skew 2"),
            new neighbor("skew 1", "skew"),
            new neighbor("skew 1", "skew 3"),
            new neighbor("substrate", "skew"),
            new neighbor("t 3", "skew"),
            new neighbor("t", "skew 2"),
            new neighbor("t 2", "skew 2"),
            new neighbor("t 1", "skew 2"),
            new neighbor("track", "skew"),
            new neighbor("track 1", "skew 2"),
            new neighbor("transition", "skew"),
            new neighbor("transition 1", "skew 2"),
            new neighbor("turn 1", "skew"),
            new neighbor("turn 2", "skew"),
            new neighbor("turn 3", "skew 2"),
            new neighbor("viad 1", "skew"),
            new neighbor("viad", "skew 2"),
            new neighbor("vias", "skew"),
            new neighbor("vias 1", "skew"),
            new neighbor("vias 2", "skew"),
            new neighbor("vias 3", "skew 2"),
            new neighbor("wire 1", "skew"),
        ],
        {
            "Chips":["component","substrate","turn","connection","corner","track","t"],
            "Turnless": ["bridge", "component", "connection", "corner", "substrate", "t", "track", "transition", "viad", "vias", "wire", "skew", "dskew"],
            "Debug":['substrate', 'turn'],
            "Test": ["component", "connection", "viad", "vias", "wire", "skew", "dskew"],
            "Test2": ["t", "track","turn"]
        }
    )
}